export const SET_USER_INFO = 'SET_USER_INFO';
export const ERR_MSG = 'ERR_MSG';
export const SET_CURRENT_MANGA = 'SET_CURRENT_MANGA';
export const SET_SECTIONS = 'SET_SECTIONS';
export const SET_CURRENT_SECTION = 'SET_CURRENT_SECTION';
