const sessionData = {
  user: JSON.parse(sessionStorage.getItem('user')),
  admin:JSON.parse(sessionStorage.getItem('admin')),
  currentManga: JSON.parse(sessionStorage.getItem('curManga')),
  sections: JSON.parse(sessionStorage.getItem('sections')),
  currentSection: JSON.parse(sessionStorage.getItem('currentSection')),
  tags: JSON.parse(sessionStorage.getItem('tags')),
  historyRead: JSON.parse(localStorage.getItem('historyRead')),
  searchResult: JSON.parse(sessionStorage.getItem('searchResult')),
  authorManga: JSON.parse(sessionStorage.getItem('authorManga')),
  mangaData: JSON.parse(sessionStorage.getItem('mangaData')),
  mangaForm: JSON.parse(sessionStorage.getItem('mangaForm')),
  mangeId: JSON.parse(sessionStorage.getItem('mangaId')),
  mangaTitlePage: JSON.parse(sessionStorage.getItem('mangaTitlePage')),
  chapterData: JSON.parse(sessionStorage.getItem('chapterData')),
  tableData: JSON.parse(sessionStorage.getItem('tableData')),
  tableColums: JSON.parse(sessionStorage.getItem('tableColums')),
  tableRowData: JSON.parse(sessionStorage.getItem('tableRowData')),
};
const state = {
  user: sessionData.user || {},
  admin: sessionData.admin || {},
  currentManga: sessionData.currentManga || {},
  sections: sessionData.sections || {},
  currentSection: sessionData.currentSection || '',
  tags: sessionData.tags || [],
  historyRead: sessionData.historyRead || [],
  searchResult: sessionData.searchResult || [],
  authorManga: sessionData.authorManga || [],
  mangaData: sessionData.mangaData || [],
  mangaForm: sessionData.mangaForm || [],
  mangaId: sessionData.mangaId || [],
  mangaTitlePage: sessionData.mangaTitlePage || [],
  chapterData: sessionData.chapterData || [],
  tableData: sessionData.tableData || [],
  tableColums: sessionData.tableColums || [],
  tableRowData: sessionData.tableRowData || [],
};
export default state;
